### ISSUE TITLE
Open API Spec v3.1.0 

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-management-openapi-spec#209]
This repo has been a lot more active recently, which is great to see ! 
As a result things might already be in motion on this 🤷

[Migrating from OpenAPI v3.0 to v3.1.0](https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0)

**Comment by bretterer** [comment]
Hey @exitcode0 ,

Thanks for this issue.  This repo is a "dist only" repo that is generated from a private repo where our main code is.  I have this tracked internally to investigate updating to 3.1, but unsure when that will happen at the moment.

Always appreciate your involvement in our repos!

**Comment by exitcode0** [comment]
> Hey @exitcode0 ,
> 
> Thanks for this issue. This repo is a "dist only" repo that is generated from a private repo where our main code is. I have this tracked internally to investigate updating to 3.1, but unsure when that will happen at the moment.
> 
> Always appreciate your involvement in our repos!

@bretterer Thanks for following this up for me!
