### ISSUE TITLE
Missing GROUP_MEMBERSHIP_ADMIN role type

### ISSUE THREAD

**Issue by pablorf-dev** [okta/okta-management-openapi-spec#73]
I'm developing with [okta-sdk-python](https://github.com/okta/okta-sdk-python), but I found that this role type is missing, receiving the following message:
```
'GROUP_MEMBERSHIP_ADMIN' is not a valid RoleType
```
I've found that the [spec doesn't list it](https://github.com/okta/okta-management-openapi-spec/blob/master/resources/spec.yaml#L13245), but [documentation does](https://developer.okta.com/docs/reference/api/roles/#role-types). I know that it was an Early Access feature, but doesn't seem anymore.

Can you provide it?

**Comment by arvindkrishnakumar-okta** [comment]
@pablorf-dev Thanks for reporting this! 

We will get this added.
